### ISSUE TITLE
Not convenient to change grandprix state

### ISSUE THREAD

**Issue by iluvatyr** [kimden/stk-code#8]
## Description
When hosting a Grandprix server,  it is necessary to finish all grandprix races before the grandprix is possible to start from start again. Meaning if someone wants to restart mid grandprix, it is necessary to restart the entire server. 

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): 
kimden-stk

## Possible Solution

Adding a admin command that can reset the grandprix state to zero races again and also resets the standings.
something like 
```
/resetgp
```

**Comment by kimden** [comment]
Should be fixed in 477b956 if it's (hopefully) done correctly, needs testing still
